Feat/menu opcoes
Estudo-continuo/multisports-initial pull request #8
Opened 2024-05-13 02:49 UTC by FernandoMoreti

Menu Opções:

Nome do campeonato selecionado
Criar 5 opções: Classificação, Proximos jogos, Ultimos jogos, Estatisticas e noticias → to do: Tornar essas opções funcionais.

![Captura de tela 2024-05-12 234855](https://github.com/Estudo-continuo/multisports-initial/assets/153198754/d672d67d-91b5-4643-bbed-c3ca30d0debe)

2024-05-13 12:18 UTC, LucasBolela requested changes
Faça as correções necessárias!

2024-05-13 12:18 UTC, LucasBolela commented on data/futebol/menu_opcoes.json
Isso aqui não está correto, a informação é dinâmica não vai existir um json falando qual está ativo!

2024-05-13 12:18 UTC, LucasBolela commented on public/js/futebol/card_apresentacao.js
O arquivo principal do conteúdo do js pode ser um index.js, não será um arquivo para cada funcionalidade. Centralizar tudo em um só

2024-05-13 12:18 UTC, LucasBolela commented on public/js/futebol/menu_opcoes.js
Unificar com o card_apresentacao, e remover todos os console.log!

2024-05-13 12:18 UTC, LucasBolela commented on views/futebol/index.html
> +<div class="organize-content">
Essa tag div aqui pode ser substituída pela tag main

2024-05-13 14:32 UTC, FernandoMoreti commented on data/futebol/menu_opcoes.json
Estou com dificuldae de implementar o dinamismo nessa seçao

2024-06-17 00:13 UTC, LucasBolela approved these changes
Aprovado!

2024-06-17 00:13 UTC, merged